# Generated by Django 4.2.27 on 2025-12-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名・屋号')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住所')),
                ('business_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='業種')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': '個人事業主',
                'verbose_name_plural': '個人事業主一覧',
            },
        ),
    ]
