# Generated by Django 4.2.27 on 2025-12-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(unique=True, verbose_name='対象年月')),
                ('is_completed', models.BooleanField(default=False, verbose_name='全体の完了フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1_waiting', '書類待ち'), ('2_received', '書類受領済'), ('3_calculated', '計算済'), ('4_billed', '請求済'), ('5_paid', '振込完了')], default='1_waiting', max_length=20, verbose_name='進捗状況')),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, max_length=10, verbose_name='勤務時間')),
                ('payment_amount', models.IntegerField(default=0, verbose_name='支払金額')),
                ('google_drive_url', models.URLField(blank=True, null=True, verbose_name='資料URL')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_app.freelancer')),
                ('monthly_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='system_app.monthlyprocess')),
            ],
            options={
                'unique_together': {('monthly_process', 'freelancer')},
            },
        ),
    ]
