# Generated by Django 4.2.27 on 2025-12-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_monthlyprocess_taskstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='base_unit_price',
            field=models.IntegerField(default=0, verbose_name='基準単価(月単価)'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='クライアント名'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='契約終了日'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='契約開始日'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='deduction_unit_price',
            field=models.IntegerField(default=0, verbose_name='控除単価(不足時)'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='lower_limit_hours',
            field=models.FloatField(default=140.0, verbose_name='精算下限時間'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='overtime_unit_price',
            field=models.IntegerField(default=0, verbose_name='超過単価(超過時)'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='案件名'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='upper_limit_hours',
            field=models.FloatField(default=180.0, verbose_name='精算上限時間'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='氏名'),
        ),
    ]
