# Generated by Django 4.2.27 on 2025-12-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0003_remove_freelancer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='actual_working_hours',
            field=models.FloatField(default=0.0, verbose_name='実稼働時間'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='calculated_amount',
            field=models.IntegerField(default=0, verbose_name='計算請求金額'),
        ),
    ]
