# Generated by Django 4.2.27 on 2026-01-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0004_taskstatus_actual_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='クライアント名')),
                ('file', models.FileField(upload_to='purchase_orders/%Y/%m/', verbose_name='注文書ファイル')),
                ('received_at', models.DateTimeField(verbose_name='メール受信日')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='保存日')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='ダウンロード回数')),
            ],
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('not_started', '未着手'), ('working', '書類待ち'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='進捗状況'),
        ),
    ]
