# Generated by Django 4.2.27 on 2026-01-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0005_purchaseorder_alter_taskstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='会社名/屋号')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当者名')),
                ('base_unit_price', models.IntegerField(verbose_name='基本単価')),
                ('lower_limit_hours', models.FloatField(verbose_name='下限時間')),
                ('upper_limit_hours', models.FloatField(verbose_name='上限時間')),
                ('overtime_unit_price', models.IntegerField(verbose_name='超過単価')),
                ('deduction_unit_price', models.IntegerField(verbose_name='控除単価')),
                ('is_active', models.BooleanField(default=True, verbose_name='稼働中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '提携パートナー',
                'verbose_name_plural': '提携パートナー一覧',
            },
        ),
    ]
